---

computername: null
hostname: null

finder_proxy_icon_hover_delay: null

safari_show_full_url_in_address_bar: null
safari_open_safe_files_automatically: null
safari_show_status_bar: null
safari_show_developer_menu: null

system_save_application_state_on_quit: null
system_expand_save_panel_by_default: null
system_expand_print_panel_by_default: null
system_show_file_extensions_warning: null
system_warn_before_emptying_the_trash: null
system_use_f_keys_as_standard_function_keys: null
system_index_network_storage_with_spotlight: null
trackpad_tap_to_click: null

screensaver_ask_for_password: null
screensaver_ask_for_password_in_seconds: null

dock_make_hidden_apps_translucent: null
dock_show_indicator_lights_for_open_apps: null
