---

- name: "Show full URL in the address bar ({{ show_full_url_in_address_bar }})"
  when: safari_show_full_url_in_address_bar != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowFullURLInSmartSearchField
    type: bool
    value: "{{ safari_show_full_url_in_address_bar }}"
  notify: Restart Safari

- name: "Open 'safe' files automatically ({{ open_safe_files_automatically }})"
  when: safari_open_safe_files_automatically != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: AutoOpenSafeDownloads
    type: bool
    value: "{{ safari_open_safe_files_automatically }}"
  notify: Restart Safari

- name: "Show status bar ({{ show_status_bar }})"
  when: safari_show_status_bar != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowOverlayStatusBar
    type: bool
    value: "{{ safari_show_status_bar }}"
  notify: Restart Safari

- name: "Show status bar ({{ show_developer_menu }})"
  when: safari_show_developer_menu != None
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: IncludeDevelopMenu
    type: bool
    value: "{{ safari_show_developer_menu|bool }}"
  notify: Restart Safari
